services:
  backend:
    image: inboxartisan/inboxartisan-back:dev
    command: sh -c "npm run build && npm run prod"
    ports:
      - 4000:4000
    env_file:
      - ./global.env
    environment:
      - PGHOST=db
      - PGHOSTEST=dbtest
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://backend:4000/graphql?query=%7B__typename%7D -H 'Apollo-Require-Preflight: true' || exit 1",
        ]
      interval: 10s
      timeout: 30s
      retries: 5

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d inboxartisan -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inboxartisan
    ports:
      - 5433:5432
    volumes:
      - inboxArtisanData:/var/lib/postgresql/data

  frontend:
    image: inboxartisan/inboxartisan-front:dev
    command: sh -c "npm run build && npm run start"
    ports:
      - 3000:3000
    env_file:
      - ./global.env
    depends_on:
      backend:
        condition: service_healthy
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  images:
    image: inboxartisan/inboxartisan-images:dev
    command: sh -c "npm run build && npm run prod"
    volumes:
      - ./images/uploads:/app/uploads
    ports:
      - 5000:8000
    env_file:
      - ./global.env

  nginx:
    image: nginx:1.21.3
    depends_on:
      - frontend
      - backend
      - images
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx

volumes:
  inboxArtisanData:
  inboxArtisanDataTest:
  web-client-build: