name: Classic CI

on:
  pull_request:
    branches-ignore:
      - dev
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    # Service de container qui seront accessible DANS demo-job
    services:
      # Label utilisé pour accéder à ce service
      postgres:
        # Image docker Hub
        image: postgres
        # health checks pour être sûr que postgres a démarré
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # mapping tcp des ports pour permettre d'ouvrir le port à l'hôte
          - 5434:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto backend and run tests
        run: cd backend && npm i && npm run test-actions
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto front and run lint
        run: cd frontend && npm i && npm run lint
