name: ci-cd-dev

on:
  pull_request:
    branches:
      - dev

  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    # Service de container qui seront accessible DANS demo-job
    services:
      # Label utilisé pour accéder à ce service
      postgres:
        # Image docker Hub
        image: postgres
        # Infos de connexion (à vous de choisir!)
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: inboxartisan_test
        # health checks pour être sûr que postgres a démarré
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # mapping tcp des ports pour permettre d'ouvrir le port à l'hôte
          - 5434:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto backend and run tests
        run: cd backend && npm i && npm run test-actions
      - name: Goto backend and run build
        run: cd backend && npm i && npm run build
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto front and run lint
        run: cd frontend && npm i && npm run lint
      - name: Goto front and run build
        run: cd frontend && npm i && npm run build
        env:
          PGHOSTTEST: localhost
  docker:
    needs: [test-front, test-backend]
    # if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push front
        uses: docker/build-push-action@v4
        with:
          push: true
          context: '{{defaultContext}}:frontend'
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inboxartisan-front:dev
      - name: Build and push back
        uses: docker/build-push-action@v4
        with:
          push: true
          context: '{{defaultContext}}:backend'
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inboxartisan-back:dev
      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          push: true
          context: '{{defaultContext}}:images'
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inboxartisan-images:dev
