name: lint-front CI

on: [pull_request]

jobs:
  continues_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Move to Front
        run: cd frontend

      - name: Install Node.js dependencies
        run: npm i

      - name: Check lint
        run: npm run lint
